// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_K8wXHdCnVq09793_rGOoLZHcpG67DWE',
    appId: '1:162532144093:web:93c2f5ac68186df5007c34',
    messagingSenderId: '162532144093',
    projectId: 'aqary-app-e2cf4',
    authDomain: 'aqary-app-e2cf4.firebaseapp.com',
    storageBucket: 'aqary-app-e2cf4.firebasestorage.app',
    measurementId: 'G-YLHY7LQS80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLoAciF9Kw5c3sUPlAz0dosjtGzppDdsY',
    appId: '1:162532144093:android:670495542c5f8c78007c34',
    messagingSenderId: '162532144093',
    projectId: 'aqary-app-e2cf4',
    storageBucket: 'aqary-app-e2cf4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2d6NuhJJq7O4GmOqfK2L_wVIpLnD1qXE',
    appId: '1:878157543892:ios:cfca056db8a6d7e44c3e41',
    messagingSenderId: '878157543892',
    projectId: 'aqarybe',
    storageBucket: 'aqarybe.firebasestorage.app',
    iosBundleId: 'com.aqary.app',
  );

}